import { Router, type IRouter } from "express";
import healthRouter from "./health";
import invitationsRouter from "./invitations";
import paymentsRouter from "./payments";
import aiRouter from "./ai";
import authRouter from "./auth";
import catalogRouter from "./catalog";
import applicationsRouter from "./applications";
import communityRouter from "./community";
import chatRouter from "./chat";
import notificationsRouter from "./notifications";
import matchRouter from "./match";
import vaultRouter from "./vault";
import capitalRouter from "./capital";
import pulseRouter from "./pulse";
import publicIdRouter from "./publicId";
import analyticsRouter from "./analytics";
import talentRouter from "./talent";
import apiKeysRouter from "./apiKeys";
import settingsRouter from "./settings";
import passesRouter from "./passes";
import stageRouter from "./stage";
import liveJobsRouter from "./liveJobs";
import orgsRouter from "./orgs";
import legalRouter from "./legal";
import campaignsRouter from "./campaigns";
import searchRouter from "./search";
import journeyRouter from "./journey";

const router: IRouter = Router();

router.use(healthRouter);
router.use(invitationsRouter);
router.use("/payments", paymentsRouter);
router.use("/ai", aiRouter);
router.use("/auth", authRouter);
router.use(journeyRouter);
router.use(catalogRouter);
router.use(applicationsRouter);
router.use(communityRouter);
router.use(chatRouter);
router.use(notificationsRouter);
router.use(matchRouter);
router.use(vaultRouter);
router.use(capitalRouter);
router.use(pulseRouter);
router.use(publicIdRouter);
router.use(analyticsRouter);
router.use(talentRouter);
router.use(apiKeysRouter);
router.use(settingsRouter);
router.use(passesRouter);
router.use(stageRouter);
router.use(liveJobsRouter);
router.use(orgsRouter);
router.use(legalRouter);
router.use(campaignsRouter);
router.use(searchRouter);

export default router;
